fixed kubeplugin

diff --git a/scripts/kubeplugin b/scripts/kubeplugin
--- a/scripts/kubeplugin
+++ b/scripts/kubeplugin
@@ -1,11 +1,16 @@
 #!/bin/bash
 
-# Define command-line arguments
+if [ "$#" -ne 2 ]; then
+    echo "Error! Wrong command format. Please use arguments: \"kubectl kubeplugin <node or pod> <namespace>\""
+    exit 1
+fi
 
-RESOURCE_TYPE=$0
+# Define command-line arguments
+RESOURCE_TYPE=$1
+NAMESPACE=$2
 
 # Retrieve resource usage statistics from Kubernetes
-kubectl $2 $RESOURCE_TYPE -n $1 | tail -n +2 | while read line
+kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
 do
   # Extract CPU and memory usage from the output
   NAME=$(echo $line | awk '{print $1}')
@@ -14,4 +19,5 @@ do
 
   # Output the statistics to the console
   # "Resource, Namespace, Name, CPU, Memory"
+  echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
 done
